version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - zadanie4

  zadanie4:
    build:
      context: ./zadanie4
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
